apiVersion: apps/v1
kind: Deployment
metadata:
  name: emailservice-prod-v1
  labels:
    app: emailservice-prod
    version: v1
spec:
  selector:
    matchLabels:
      app: emailservice-prod
      version: v1
  template:
    metadata:
      labels:
        app: emailservice-prod
        version: v1
    spec:
      serviceAccountName: kardinal-manager
      terminationGracePeriodSeconds: 5
      containers:
        - name: server
          image: kurtosistech/obd-emailservice
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"
            - name: MICRO_REGISTRY
              value: "kubernetes"
            - name: TRACING_ENABLE
              value: "true"
            - name: TRACING_JAEGER_URL
              value: "http://jaeger-collector.default.svc.cluster.local:14268/api/traces"
          readinessProbe:
            periodSeconds: 5
            exec:
              command: ["/bin/grpc_health_probe", "-addr=:8080"]
          livenessProbe:
            periodSeconds: 5
            exec:
              command: ["/bin/grpc_health_probe", "-addr=:8080"]
          # resources:
          #   requests:
          #     cpu: 100m
          #     memory: 64Mi
          #   limits:
          #     cpu: 200m
          #     memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: emailservice-prod
  labels:
    app: emailservice-prod
    version: v1
spec:
  type: ClusterIP
  selector:
    app: emailservice-prod
  ports:
    - name: grpc
      port: 5000
      targetPort: 8080
