apiVersion: apps/v1
kind: Deployment
metadata:
  name: paymentservice-v1
  labels:
    app: paymentservice
    version: v1
spec:
  selector:
    matchLabels:
      app: paymentservice
      version: v1
  template:
    metadata:
      labels:
        app: paymentservice
        version: v1
    spec:
      serviceAccountName: go-micro
      terminationGracePeriodSeconds: 5
      containers:
        - name: server
          image: kurtosistech/obd-paymentservice
          ports:
            - containerPort: 50051
          env:
            - name: PORT
              value: "50051"
            - name: MICRO_REGISTRY
              value: "kubernetes"
            - name: TRACING_ENABLE
              value: "true"
            - name: TRACING_JAEGER_URL
              value: "http://jaeger-collector.default.svc.cluster.local:14268/api/traces"
          readinessProbe:
            exec:
              command: ["/bin/grpc_health_probe", "-addr=:50051"]
          livenessProbe:
            exec:
              command: ["/bin/grpc_health_probe", "-addr=:50051"]
          # resources:
          #   requests:
          #     cpu: 100m
          #     memory: 64Mi
          #   limits:
          #     cpu: 200m
          #     memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: paymentservice
  labels:
    app: paymentservice
    version: v1
spec:
  type: ClusterIP
  selector:
    app: paymentservice
  ports:
    - name: grpc
      port: 50051
      targetPort: 50051
